name: "helium: lint"

on:
  push:
    paths:
      - "helium/**"
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - "helium/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./helium
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install ".[test]"

      - name: Test with pyright
        uses: jakebailey/pyright-action@v1
        with:
          working-directory: ./helium
